version: "3.8"

services:
  pokemon-api:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pokemon
    depends_on:
      - db
    networks:
      - pokemanapi_pokemanapi_default

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pokemon
    networks:
      - pokemanapi_pokemanapi_default
    volumes:
      - /data/postgres_data:/var/lib/postgresql/data

networks:
  pokemanapi_pokemanapi_default: